name: Build Executable

on:
    push:
        paths:
            - main.py
            - .github/workflows/main.yaml
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11.9'

          - name: Install libraries
            run: |
                pip install pyinstaller
                pip install PyMemoryEditor
                pip install pypresence

          - name: Build executable
            run: pyinstaller --onefile main.py

          - name: Upload executable
            uses: actions/upload-artifact@v4
            with:
              name: tirpc
              path: dist/main
